[info]
name = "Asteraus"
version = "0.1.1 beta"
date = 2024-08-05
developers = [
    {Name = "Ilya Belov", email = "ibelov.projects@gmail.com", url = "https://github.com/Sirine-Chi"}
]
collaborators = [
    {Name = "Kamilfo-Developer", url = "https://github.com/Kamilfo-Developer"}
]
